CREATE TABLE tb_usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    tipo_usuario VARCHAR(255) NOT NULL
);

CREATE TABLE tb_lancamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    valor NUMERIC(19, 2) NOT NULL,
    data TIMESTAMP NOT NULL,
    tipo_operacao VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_lancamento_usuario FOREIGN KEY (usuario_id) REFERENCES tb_usuarios (id)
);